'use client'

import { motion } from 'framer-motion'
import { MessageSquare, Heart, Repeat, Share } from 'lucide-react'

export default function Examples() {
  const exampleThread = [
    "🚀 Want to boost your productivity? Here's a simple framework that changed my life:",
    "📋 The 2-Minute Rule: If a task takes less than 2 minutes, do it immediately. No excuses, no delays. This small habit prevents tiny tasks from piling up into overwhelming mountains.",
    "⏰ Time Blocking: Schedule your most important work in 90-minute focused blocks. Your brain works best in these natural cycles. No meetings, no interruptions, just deep work.",
    "🎯 The 80/20 Principle: 80% of your results come from 20% of your efforts. Identify your high-impact activities and focus ruthlessly on them. Stop doing busy work.",
    "💡 Pro tip: Start your day with your most challenging task. Your willpower is highest in the morning. Don't waste it on emails and admin work.",
    "What's your biggest productivity challenge? Drop a ❤️ if this helps and share your own tips below! #ProductivityHacks #TimeManagement"
  ]

  return (
    <section className="x-container py-8 sm:py-12 lg:py-16">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        viewport={{ once: true }}
        className="text-center mb-8 sm:mb-12"
      >
        <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-black dark:text-white mb-4">
          See It In Action
        </h2>
        <p className="text-gray-600 dark:text-gray-300 text-base sm:text-lg max-w-2xl mx-auto">
          Here's an example of a viral tweet thread generated by ThreadCraft
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.2 }}
        viewport={{ once: true }}
        className="max-w-2xl mx-auto"
      >
        <div className="space-y-4">
          {exampleThread.map((tweet, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="x-card"
            >
              <div className="flex items-start gap-3">
                <div className="x-avatar">
                  TC
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="font-semibold text-black dark:text-white">
                      ThreadCraft
                    </span>
                    <span className="text-gray-500 dark:text-gray-400 text-sm">
                      @threadcraft
                    </span>
                    <span className="text-gray-500 dark:text-gray-400 text-sm">
                      ·
                    </span>
                    <span className="text-gray-500 dark:text-gray-400 text-sm">
                      {index + 1}h
                    </span>
                  </div>
                  
                  <p className="text-black dark:text-white text-base leading-relaxed mb-3">
                    {tweet}
                  </p>
                  
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-6 text-gray-500 dark:text-gray-400">
                      <button className="flex items-center gap-1 hover:text-red-500 transition-colors">
                        <Heart className="w-4 h-4" />
                        <span className="text-sm">1.2K</span>
                      </button>
                      <button className="flex items-center gap-1 hover:text-green-500 transition-colors">
                        <Repeat className="w-4 h-4" />
                        <span className="text-sm">456</span>
                      </button>
                      <button className="flex items-center gap-1 hover:text-blue-500 transition-colors">
                        <MessageSquare className="w-4 h-4" />
                        <span className="text-sm">89</span>
                      </button>
                      <button className="flex items-center gap-1 hover:text-blue-500 transition-colors">
                        <Share className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          viewport={{ once: true }}
          className="text-center mt-8"
        >
          <p className="text-gray-600 dark:text-gray-400 text-sm mb-4">
            This thread generated 2.1K+ impressions and 156 retweets
          </p>
          <button
            onClick={() => document.getElementById('generator')?.scrollIntoView({ behavior: 'smooth' })}
            className="x-button px-6 py-3 text-base"
          >
            Create Your Own Thread
          </button>
        </motion.div>
      </motion.div>
    </section>
  )
} 